#!/usr/bin/env bash

# head /dev/urandom | tr -dc A-Za-z0-9 | cut -c1-8 | http put http://172.17.0.2:8500/v1/kv/common-aa

app_name=$(grep '@app_name :' mix.exs | awk '{print $2}')

PROJECT_NAME=${app_name:1}

set -euxo pipefail

rm -Rf cli/devOps/files/app/*.gz

option=${1:-a}

case ${option} in
      a)
      mix deps.get --only prod
      RELEASE_TAR_NAME_SUFFIX=$(git rev-parse --verify HEAD | cut -c1-6) MIX_ENV=prod mix release --overwrite
      ;;

      s)
      MIX_ENV=prod mix release --overwrite
      ;;

esac

cd cli/devOps

version=$(cut -d' ' -f2 "files/app/build/${PROJECT_NAME}/releases/start_erl.data")

image_organization="docker.io/jalbert"
image_name="${image_organization}/${PROJECT_NAME}"

rm template.json || true

cat ubuntu.json \
    | jj -v ${image_name} -O post-processors.0.0.repository \
    | jj -v ${version} -O post-processors.0.0.tag \
    > template.json \

cd files/app

export APP_TAR_GZ_FILE=$(ls *.gz | head -n 1)
cd ../..
packer build template.json
